### ISSUE TITLE
Animate/Draw Sprites

### ISSUE THREAD

**Issue by nazthesilly** [Showrunners/fnf#1]
Ruby - X
Toasty - ✅
Sil(etrus) - X
Zestrial - X
Dezvoru - X
Argnorac - X
Raivul - X
Coin - X
Dream - X

Will be edited/updated as the team does the sprite-work.

**Comment by suitedreamer** [comment]
Just to add, Toasty has no animation yet, and is currently just having the main symbols drawn.

**Comment by nazthesilly** [comment]
@InkyTheBlue hey could you draw icons for toasty? make sure it's 300x150 pixels and the losing icon is on the right side (and also that the two icons don't cross the middle of the image!!)

**Comment by nazthesilly** [comment]
realized that i should probably refine the artwork so the mod doesn't look like a sketch, so toasty is back at 50%. woops

**Comment by nazthesilly** [comment]
ik toasty has been completed for a while but I fixed some buggyness with his anims ingame and added the icons. 👍

**Comment by Christian-Toney** [comment]
closing this because i think it'll be organized if we assign people per issue
