### ISSUE TITLE
Find another voice actor for Ruby

### ISSUE THREAD

**Issue by Christian-Toney** [Showrunners/fnf#16]

**Comment by Christian-Toney** [comment]
this is a priority for me because it could affect the main game

**Comment by nazthesilly** [comment]
SOLUTION!!!! we make undertale 2

**Comment by Christian-Toney** [comment]
Hm, I'm liking it

**Comment by Christian-Toney** [comment]
@nova-grace is now the voice actor for Ruby; this might or might not change for the main game
