### ISSUE TITLE
Create Music

### ISSUE THREAD

**Issue by nazthesilly** [Showrunners/fnf#3]
[See this page for more info](https://toyhou.se/~world/23541.the-showrunners/page/46553.friday-night-funkin-mod)

### Before week 1

Main Menu - X

### **--Week 1**

Seminar - X

Damnation - X

Temporal - X

### **--Week 2**

Interrogation - X

Sweet Talk - X

Dominance - X

### **--Week 3**

Disturbance - X

Fast Food - X

Loyal Customer - X

### **--Week 4**

The Best - X

The Best of the Best - X

The Best of the Best of the Best - X

@Sudobeast I just wanna compliment those artistic names for week 4

### **--Week 5**

Resent - X

Silence - X

Mine - X

### **--Week 6**

Litigation (Funk the World Remix) - X

Non-negotiable - X

Hostile Takeover - X

### **--Secret/Bonus Songs**

Summary (Season Complete Remix) - X

**Comment by Christian-Toney** [comment]
see https://github.com/Showrunners/fnf/issues/1#issuecomment-1024848820
